[View in Colaboratory](https://colab.research.google.com/github/karangautam/Learning-Samples/blob/master/DanburyAI.ipynb)

In [1]:
# Run this cell and select the kaggle.json file downloaded
# from the Kaggle account settings page.
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"karangautam","key":"7886fb75a6cbe6a3bf59d84dcbab4904"}'}

In [2]:
!ls -lha kaggle.json
# Next, install the Kaggle API client.
!pip install -q kaggle
# The Kaggle API client expects this file to be in ~/.kaggle,
# so move it there.
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

# This permissions change avoids a warning on Kaggle tool startup.
!chmod 600 /content/.kaggle/kaggle.json

-rw-r--r-- 1 root root 67 Jun 16 12:27 kaggle.json


In [46]:
# List available datasets.
!kaggle competitions list

ref                                             deadline             category            reward  teamCount  userHasEntered  
----------------------------------------------  -------------------  ---------------  ---------  ---------  --------------  
house-prices-advanced-regression-techniques     2030-01-01 00:00:00  Getting Started  Knowledge       5116            True  
digit-recognizer                                2030-01-01 00:00:00  Getting Started  Knowledge       2679            True  
titanic                                         2030-01-01 00:00:00  Getting Started  Knowledge      11490            True  
imagenet-object-detection-challenge             2029-12-31 07:00:00  Research         Knowledge          0           False  
imagenet-object-detection-from-video-challenge  2029-12-31 07:00:00  Research         Knowledge          0           False  
imagenet-object-localization-challenge          2029-12-31 07:00:00  Research         Knowledge         16           False  


In [4]:
!kaggle competitions download -c dai-june

  0%|                                               | 0.00/43.0k [00:00<?, ?B/s]
100%|██████████████████████████████████████| 43.0k/43.0k [00:00<00:00, 22.3MB/s]
  0%|                                                 | 0.00/360 [00:00<?, ?B/s]
100%|███████████████████████████████████████████| 360/360 [00:00<00:00, 462kB/s]
 87%|█████████████████████████████████▏    | 75.0M/85.8M [00:01<00:01, 11.2MB/s]
100%|██████████████████████████████████████| 85.8M/85.8M [00:01<00:00, 53.8MB/s]
 88%|███████████████████████████████████     | 113M/129M [00:02<00:00, 17.8MB/s]
100%|████████████████████████████████████████| 129M/129M [00:02<00:00, 53.2MB/s]


In [47]:
from subprocess import check_output
print(check_output(["ls", "../content/.kaggle/competitions/dai-june"]).decode("utf8"))
#print(check_output(["ls", "../content/.kaggle/competitions/whale-categorization-playground/train/train"]).decode("utf8"))


example_submission.csv
test.npy
train_x.npy
train_y.npy



In [0]:
import keras
from keras import layers
from keras import models

In [0]:
from keras.applications import VGG16

conv_base = VGG16(weights='imagenet',
                  include_top=False,
                  input_shape=(48, 48, 3))

In [0]:
import pandas as pd
import numpy as np

In [0]:
base_dir = '../content/.kaggle/competitions/dai-june'
x_train= np.load('../content/.kaggle/competitions/dai-june/train_x.npy')
y_train = np.load('../content/.kaggle/competitions/dai-june/train_y.npy')

In [0]:
trainX= x_train.astype('float32')


In [0]:
trainX /= 255

In [54]:
y_train.dtype

dtype('uint8')

In [55]:
y_train[0:99]

array([ 8,  2,  1,  5,  5,  5,  2,  1,  6,  6,  2,  2,  9,  7,  1,  2,  7,
        3,  5,  4,  1,  4,  8,  4,  4,  2,  1,  2,  5,  2,  5,  4,  9,  2,
        8,  3,  7,  7,  1,  2, 10,  1,  1,  3,  6,  3,  1,  7,  3,  2,  2,
        2,  2,  2,  9,  4,  2,  5, 10,  2,  5, 10,  1,  2,  7,  1,  7,  1,
        1,  7,  2,  8, 10, 10,  3,  1,  6,  8,  1,  6,  5,  4,  5, 10,  4,
        2,  4,  1,  4,  1,  3,  3,  7,  4,  1,  2,  2,  6,  2],
      dtype=uint8)

In [0]:
n_classes = 11
trainY = keras.utils.to_categorical(y_train, n_classes)


In [57]:
trainX.shape

(43954, 32, 32, 3)

In [0]:
model = models.Sequential()

model.add(layers.Conv2D(32,(3,3),activation='relu',input_shape=(32,32,3),padding='same'))
#model.add(layers.MaxPooling2D(2,2))
model.add(layers.Conv2D(32,(3,3),activation='relu',padding='same'))
model.add(layers.Conv2D(32,(3,3),activation='relu',padding='same'))
model.add(layers.BatchNormalization())
model.add(layers.MaxPooling2D(2,2))

model.add(layers.Conv2D(64,(3,3),activation='relu',padding='same'))
model.add(layers.Conv2D(64,(3,3),activation='relu',padding='same'))
model.add(layers.Conv2D(64,(3,3),activation='relu',padding='same'))
model.add(layers.BatchNormalization())
model.add(layers.MaxPooling2D(2,2))
model.add(layers.Conv2D(128,(3,3),activation='relu',padding='same'))
model.add(layers.Conv2D(128,(3,3),activation='relu',padding='same'))
model.add(layers.Conv2D(128,(3,3),activation='relu',padding='same'))
model.add(layers.BatchNormalization())
model.add(layers.MaxPooling2D(2,2))
model.add(layers.Conv2D(256,(3,3),activation='relu',padding='same'))
model.add(layers.Flatten())

model.add(layers.Dense(128,activation='relu'))
model.add(layers.Dropout(0.50))
model.add(layers.BatchNormalization())
model.add(layers.Dense(64,activation='relu'))
model.add(layers.Dropout(0.50))
model.add(layers.BatchNormalization())
model.add(layers.Dense(32,activation='relu'))

model.add(layers.Dense(11,activation='softmax'))

In [67]:
model.compile(loss='categorical_crossentropy',metrics=['accuracy'],optimizer='adam')
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_40 (Conv2D)           (None, 32, 32, 32)        896       
_________________________________________________________________
conv2d_41 (Conv2D)           (None, 32, 32, 32)        9248      
_________________________________________________________________
conv2d_42 (Conv2D)           (None, 32, 32, 32)        9248      
_________________________________________________________________
max_pooling2d_13 (MaxPooling (None, 16, 16, 32)        0         
_________________________________________________________________
conv2d_43 (Conv2D)           (None, 16, 16, 64)        18496     
_________________________________________________________________
conv2d_44 (Conv2D)           (None, 16, 16, 64)        36928     
_________________________________________________________________
conv2d_45 (Conv2D)           (None, 16, 16, 64)        36928     
__________

In [68]:
history=model.fit(trainX,trainY,epochs=50,verbose=2,batch_size=128)

Epoch 1/50
 - 25s - loss: 0.2016 - acc: 0.9550
Epoch 2/50
 - 23s - loss: 0.1554 - acc: 0.9642
Epoch 3/50
 - 23s - loss: 0.1371 - acc: 0.9676
Epoch 4/50
 - 23s - loss: 0.1324 - acc: 0.9688
Epoch 5/50
 - 23s - loss: 0.1320 - acc: 0.9687
Epoch 6/50
 - 23s - loss: 0.1077 - acc: 0.9744
Epoch 7/50
 - 23s - loss: 0.1108 - acc: 0.9737
Epoch 8/50
 - 23s - loss: 0.1066 - acc: 0.9747
Epoch 9/50
 - 23s - loss: 0.0905 - acc: 0.9786
Epoch 10/50
 - 23s - loss: 0.0907 - acc: 0.9782
Epoch 11/50
 - 23s - loss: 0.0857 - acc: 0.9797
Epoch 12/50
 - 23s - loss: 0.0892 - acc: 0.9780
Epoch 13/50
 - 23s - loss: 0.0837 - acc: 0.9801
Epoch 14/50
 - 23s - loss: 0.0885 - acc: 0.9790
Epoch 15/50
 - 23s - loss: 0.0760 - acc: 0.9817
Epoch 16/50
 - 23s - loss: 0.0770 - acc: 0.9812
Epoch 17/50
 - 23s - loss: 0.0741 - acc: 0.9818
Epoch 18/50
 - 23s - loss: 0.0708 - acc: 0.9830
Epoch 19/50
 - 23s - loss: 0.0772 - acc: 0.9816
Epoch 20/50
 - 23s - loss: 0.0738 - acc: 0.9820
Epoch 21/50
 - 23s - loss: 0.0637 - acc: 0.9853
E

 - 23s - loss: 0.0505 - acc: 0.9880
Epoch 47/50
 - 23s - loss: 0.0503 - acc: 0.9877
Epoch 48/50
 - 23s - loss: 0.0415 - acc: 0.9901
Epoch 49/50
 - 23s - loss: 0.0377 - acc: 0.9908
Epoch 50/50
 - 23s - loss: 0.0464 - acc: 0.9886


In [0]:
X_test= np.load('../content/.kaggle/competitions/dai-june/test.npy')

In [0]:
X_test= X_test.astype('float32')

In [0]:
X_test /= 255

In [0]:
predictions = model.predict(X_test)

In [0]:
from sklearn.preprocessing import LabelEncoder
from numpy import argmax
label_encoder= LabelEncoder()
inverse = predictions.argmax(1)

In [74]:
inverse

array([9, 6, 8, ..., 5, 1, 6])

In [75]:
inverse[0:99]

array([ 9,  6,  8,  1,  2,  5,  4,  9,  6, 10,  2, 10,  7, 10,  1,  3,  6,
        6,  3,  5,  9,  1,  1,  7,  2,  2, 10,  6,  5,  7,  4,  4,  1,  6,
        2,  2,  1,  8,  1,  6,  7,  1,  2,  3,  1,  2,  1,  1,  1,  6,  5,
        2,  1,  8,  5,  5,  2,  5,  1,  1,  3,  3,  1,  6,  4,  6,  3,  7,
        7,  4,  5,  3,  2,  1,  4,  1,  7,  7,  1,  3, 10,  2,  2,  5,  9,
        9,  2,  4,  2,  3,  5,  1,  5,  4,  1,  9,  1, 10,  4])

In [0]:
predictions=inverse

In [0]:
submissions=pd.DataFrame({"id": list(range(0,len(predictions))),
                         "label": predictions})


In [0]:
from google.colab import files

submissions.to_csv('df.csv',index=False, header=True)
files.download('df.csv')